### ISSUE TITLE
Move conceptual docs to the doc repo

### ISSUE THREAD

**Issue by roji** [npgsql/doc#10]
At the moment our conceptual (non-API) docs lives in each specific project's repo, under a `doc` directory. The doc repo (this repo) uses git submodules to include the three projects and access those directories. The logic here was that documentation changes should be part of the same commit which implements the feature.

In practice, this doesn't seem to have worked well:
* Documentation is frequently written later and in a separate commit: devs don't necessarily have time when developing the feature to also write full docs.
* Doc commits are done in the work branch (dev), and then have to be cherry-picked to master, pushed to github, and only then can the git submodule be updated in the doc repo. This is a very heavy and cumbersome flow.
* Our project's git history becomes cluttered with doc commits.

Instead, I propose we just move all *conceptual* docs to this repo and be done with it. Updates can be done directly in the repo, without touching the project repos, and the flow will be much lighter.

Note that we'll still use git submodules to access the code in the main repos, in order to generate API docs.

Any objections?

/cc @YohDeadfall @austindrenski

**Comment by austindrenski** [comment]
There are not enough reaction emojis to register my approval, but yeah this sounds good to me.

**Comment by YohDeadfall** [comment]
It's a good idea. I think that at the end we should get a bot which will replace sub modules, mirror documentation changes in main repos and generate pages automatically.

**Comment by roji** [comment]
Agreed this needs to be automated... I think git submodules are a good approach for API documentation (instead of mirroring), but we could simply set up a CI step in the normal repos (e.g. npgsql) which triggers an update of the submodules in the doc repo and a rebuild.

We have https://github.com/npgsql/npgsql/issues/2168 for tracking this, although we're probably not going to do this anytime soon :) It's also much less important now that we'll move the conceptual docs.
