### ISSUE TITLE
How to get output extra information about MERGE operation

### ISSUE THREAD

**Issue by sergeykorobeynikov** [npgsql/doc#155]
Hello guys!

How to I can get access to information about updated/deleted/inserted/default inserts/no action rows for MERGE operation using npgsql?

Quoting from the [official documentation](https://www.postgresql.org/message-id/attachment/23520/sql-lock.html):
> The number of rows updated, inserted or deleted is not available as part of the command tag. An optional NOTIFY message can be generated to present this information, if desired.
> 
> NOTIFY:  34 rows processed: 11 updated, 5 deleted, 15 inserted, 3 default inserts, 0 no action

As far as I understand, I can force pgsql to display this information, including in JSON form, and then deserialize it.
How to do it?

**Comment by roji** [comment]
In PostgreSQL, MERGE isn't supported AFAIK, see F312 on the [unsupported features page](https://www.postgresql.org/docs/14/unsupported-features-sql-standard.html). Use `INSERT ... ON CONFLICT DO UPDATE` instead (known as UPSERT) - this is a powerful and standard SQL mechanism. I'm not sure where that doc page you linked to comes from, but it is not in the official PostgreSQL docs.

For NOTIFY messages, you can register an event handler on NpgsqlConnection.Notice - it's fired whenever Npgsql receives a NOTICE message from PostgreSQL.

**Comment by sergeykorobeynikov** [comment]
It's a pity, I thought [the ice was broken](https://habr.com/ru/company/postgrespro/blog/412605/).
We will use this way.

**Comment by sergeykorobeynikov** [comment]
Off topic, but still.
If we use INSERT ... ON CONFLICT DO UPDATE. Is it possible to get data about new and updated records without creating new columns in the tables?

**Comment by roji** [comment]
@sergeykorobeynikov that's more of a PostgreSQL question (not really related to Npgsql). I think you can always append a RETURNING clause to get back the final columns in the row, which may be what you're looking for.

**Comment by sergeykorobeynikov** [comment]
I looked at RETURNING, but it does not support aggregate functions, and displays all records with which it works, which is not suitable.

**Comment by sergeykorobeynikov** [comment]
More...
After exec INSERT ... ON CONFLICT DO UPDATE (with pgAdmin 4) we can see information:

> INSERT 0 0
> Query returned successfully in 249 msec.

First digit after INSERT it is count of inserted rows, second — count of updated rows. How to we can get this information with npgsql?

**Comment by roji** [comment]
> First digit after INSERT it is count of inserted rows, second — count of updated rows. How to we can get this information with npgsql?

I don't think that's true. Take a look at the docs for the CommandComplete message in the [PostgreSQL protocol docs](https://www.postgresql.org/docs/current/protocol-message-formats.html):

> For an INSERT command, the tag is INSERT oid rows, where rows is the number of rows inserted. oid used to be the object ID of the inserted row if rows was 1 and the target table had OIDs, but OIDs system columns are not supported anymore; therefore oid is always 0.

So the two numbers aren't inserted and updated, they're oid (deprecated, always zero) and inserted.

**Comment by roji** [comment]
The second number (inserted) is available via [DbDataReader.RecordsAffected](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.recordsaffected?view=net-6.0#System_Data_Common_DbDataReader_RecordsAffected).

**Comment by sergeykorobeynikov** [comment]
Very strange and annoying...
