### ISSUE TITLE
Keyword not supported: max pool size

### ISSUE THREAD

**Issue by malthe** [npgsql/doc#17]
### The issue

I'm running into this issue and have been unable to track down why it happens. The "Max Pool Size" connection string keyword _should_ be supported but somehow isn't.

```
Exception has occurred: CLR/System.ArgumentException
Exception thrown: 'System.ArgumentException' in System.Data.Common.dll: 'Keyword not supported: max pool size'
   at Npgsql.NpgsqlConnectionStringBuilder.GetProperty(String keyword)
   at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection.GetPoolAndSettings()
```

### Further technical details

Npgsql version: 4.1.1
PostgreSQL version: 11
Operating system: Linux

**Comment by roji** [comment]
> But there is MinPoolSize reference (not formatted as code) in the conceptual docs, which could be a little confusing

Agreed that this is confusing - have just pushed a fix for this and other similar issues in the connection string parameter page.

Also transferred this issue to the docs repo - we should start using that repo for all conceptual doc issues/tasks.
