### ISSUE TITLE
Typo in Commands Section of Basic Usage

### ISSUE THREAD

**Issue by allprogrammers** [npgsql/doc#187]
[Basic Usage](https://www.npgsql.org/doc/basic-usage.html#commands)

Current:

>The command contains the SQL to be executed, as **wel** as any parameters (see the [parameters section](https://www.npgsql.org/doc/basic-usage.html#parameters) below). Commands can be executed in the following three ways:

Suggested:
>The command contains the SQL to be executed, as **well** as any parameters (see the [parameters section](https://www.npgsql.org/doc/basic-usage.html#parameters) below). Commands can be executed in the following three ways:

**Comment by roji** [comment]
@allprogrammers thanks, fixed this via d0b0143.

I see you did a PR in your own repo - the idea is to submit a PR against the source (upstream) repo, i.e. this one. This way I can merge your PR with the fix directly (for next time).

**Comment by allprogrammers** [comment]
yes i am new. i made a mistake thanks

**Comment by roji** [comment]
Sure thing, thanks!
