### ISSUE TITLE
Add documentation to NpgsqlLogger to make it easier to create custom loggers.

### ISSUE THREAD

**Issue by monty241** [npgsql/doc#21]
Version 3.2.5.

The class NpgsqlLogger and some interfaces define the methods such as IsEnabled and Log.

It seems that connectorId means: no connector. Maybe it is better to make it int?. 

But in general, it would be easier to understand for developers writing a logger to add some documentation to the methods and their arguments.

Now it requires a download of npgsql itself and looking at the code to what it means.

Also, it might be handy when the Log method accept an object of a LogEvent class or alike. That class might define something like a unique message code to ease identification of what a message means.

Also, it might be handy to check whether `bool Enabled` is actually called ever.

**Comment by roji** [comment]
Closing this as we're switching to Microsoft.Extensions.Logging for 7.0, see #2103. Documenting that is covered by #166.
