### ISSUE TITLE
Clarify transactional behaviour for bulk copies

### ISSUE THREAD

**Issue by svdHero** [npgsql/doc#211]
I want to import multiple CSV files within a single transaction into my Postgres database, i.e., if any of the CSV file imports fails, all imports should be rolled back.

Bulk copy for CSV is explained [here](https://www.npgsql.org/doc/copy.html#text-copy). However, I am not sure if this happens all within the same transaction, especially when using different writers. So let's assume I do this:
```cs
NpgsqlTransaction transaction = conn.BeginTransaction();
using (var fooWriter = conn.BeginTextImport("COPY foo (field_text, field_int4) FROM STDIN")) {
    fooWriter.Write("HELLO FOO\t1\n");
    fooWriter.Write("GOODBYE\t2\n");
}
using (var barWriter = conn.BeginTextImport("COPY bar (field_text, field_int4) FROM STDIN")) {
    barWriter.Write("HELLO BAR\t1\n");
    barWriter.Write("GOODBYE\t2\n");
}
transaction.Commit();
```
in order to import data to a table called `foo` and a table called `bar`.

When either the import to `bar` fails, or `transaction.Rollback()` is called, is the import to `foo` rolled back, too? I think it would help to clarify this in the docs.

Furthermore, for the [Binary Copy](https://www.npgsql.org/doc/copy.html#binary-copy) the explanation about `writer.Complete()`:

> When you've finished, you must call Complete() to save the data; not doing so will cause the COPY operation to be rolled back when the writer is disposed (this behavior is important in case an exception is thrown).

seems to imply that either a commit or a rollback happens already when the Writer is disposed. How does this relate to my question above and what is the relationship between Writer lifecycle / scope and the NpgsqlTransaction instance in the context of binary bulk copies?

**Comment by roji** [comment]
Bulk import is covered by transactionality just like anything else you do on the database: if an explicit transaction is started on the connection via BeginTransaction, nothing will get actually committed until you commit the transaction. The Complete call simply completes the import, but the import is still covered by the transaction, and so can be either committed or rolled back.

**Comment by svdHero** [comment]
@roji thank you for clarifying. Maybe your comment could be added to the documentation, e.g., as an addition to the `Writer.Complete()` description? This might help other newbies like myself.

**Comment by roji** [comment]
Nobody has yet asked this question - it seems to be clear to most people that BeginTextImport participates in the transaction just like any other database operation. If more people flag this as unclear, we can definitely update the docs.

**Comment by svdHero** [comment]
Okay. Thanks again for your quick answer.
