### ISSUE TITLE
[Doc]: About parameter upper limit

### ISSUE THREAD

**Issue by naoki4444** [npgsql/doc#233]
When I upgraded Npgsql from 2.2 to 3.0, SQL running in 2.2 failed in 3.0.
The SQL that caused the error specifies a value that exceeds the parameter by 65535.

I understood from thread [1] that the error was caused by:
Until Npgsql2.2, parameters were expanded in SQL statements in Npgsql before being sent to the server.
Since Npgsql3.0, parameters have been changed to be processed on the server side, 
and the number of parameters exceeding 65535 cannot be handled.
Therefore, the upper limit of the parameter was reached and an error occurred.

I checked the release notes [2] for this change, but it is not listed.
Could you please list this change in the release notes?
I think this falls under the breaking change mentioned in the release notes.

>The following is a non-exhaustive list of things that changed. 
>If you run against a breaking change not documented here, please let us know and we'll add it.

[1] https://github.com/npgsql/npgsql/issues/858
[2] https://www.npgsql.org/doc/release-notes/3.0.html

**Comment by Emill** [comment]
I don't think anyone thought people would actually use that many parameters.

I just found https://klotzandrew.com/blog/postgres-passing-65535-parameter-limit which has an interesting workaround when inserting multiple values, to send everything column by column instead, as arrays. Maybe we can list that workaround in the docs.

**Comment by naoki4444** [comment]
Thank you for listing it in the release note.
