### ISSUE TITLE
Link to "Legacy PostGIS" is blank.

### ISSUE THREAD

**Issue by ericmutta** [npgsql/doc#239]
On the documentation site, the navigation links on the left side seem to have a link that points nowhere:

![image](https://user-images.githubusercontent.com/20465797/189509097-3fa7f7c0-6eb0-4ffb-9d88-0060c8c2786c.png)

Looking at the HTML for the page in Chrome DevTools shows the `<a>` tag is used without an `href` attribute:

![image](https://user-images.githubusercontent.com/20465797/189509141-156763f6-cb5b-4e22-a34f-5a0e9cf50d08.png)

Should the link be removed?

**Comment by roji** [comment]
Thanks, I've fixed the link.
