### ISSUE TITLE
Cross-references in XML docs not rendering.

### ISSUE THREAD

**Issue by ericmutta** [npgsql/doc#243]
In the [XML docs](https://github.com/ericmutta/npgsql/blob/main/src/Npgsql/NpgsqlCommand.cs#L209) for the `NpgsqlCommand.CommandType` member we can see references to `System.Data.CommandType` and `System.Data.CommandType.Text` as follows:

![image](https://user-images.githubusercontent.com/20465797/189727367-64e3616e-505e-40f4-91a8-5b84c2c28310.png)

However the [output on the docs site](https://www.npgsql.org/doc/api/Npgsql.NpgsqlCommand.html#Npgsql_NpgsqlCommand_CommandType) doesn't show links or text for those references, instead we have this:

![image](https://user-images.githubusercontent.com/20465797/189728040-e1421b38-279c-47c2-a82a-5d8061c93c51.png)

What gives?

**Comment by ericmutta** [comment]
A similar thing happens with `UpdatedRowSource` which looks like this in code:

![image](https://user-images.githubusercontent.com/20465797/189730185-17a1050e-a398-4180-a1a0-2be0c693a8dc.png)


...but renders like this on the [docs site](https://www.npgsql.org/doc/api/Npgsql.NpgsqlCommand.html#Npgsql_NpgsqlCommand_UpdatedRowSource):

![image](https://user-images.githubusercontent.com/20465797/189730383-9595dd81-79af-4884-9e09-a1d1aae67ee1.png)

**Comment by roji** [comment]
@ericmutta this happens with references to types which are outside this repo (i.e. in System.Data). References within the repo seem to render well (e.g. [NpgsqlCommand.Connection](https://www.npgsql.org/doc/api/Npgsql.NpgsqlCommand.html#Npgsql_NpgsqlCommand_Connection)).

IIRC it may be possible to point docfx (the tool that generates our documentation) to XML documentation for the .NET runtime, which would mean our docs point to the standard .NET docs, but I've never had the time to exlpore this more deeply. You're of course welcome to look into this if you're interested, but I'm not sure it's going to be trivial or even possible (not sure that there are accessible XML doc files for the .NET runtime APIs).

**Comment by ericmutta** [comment]
@roji it looks like others faced [the same issue](https://github.com/dotnet/docfx/issues/7245) and a fix was [pushed to the DocFX repo](https://github.com/dotnet/docfx/pull/7325) last year, where unresolved references just render the text "as is" instead of removing it entirely. If we are not already using the latest version of DocFX, perhaps updating to the latest version may fix the issue?

**Comment by roji** [comment]
We're currently using [2.59.2](docfx https://github.com/dotnet/docfx/releases?page=2) which was released in April 2022, whereas https://github.com/dotnet/docfx/pull/7325 looks like it was merged - and the commit is even reachable from the v2.59.2 tag.. so maybe that fix is insufficient for our case...

(submitted #244 to bump to 2.59.4, the latest v2)

**Comment by YohDeadfall** [comment]
@roji, this seems to be working fine.
