### ISSUE TITLE
API docs for Npqsql points to efcore API

### ISSUE THREAD

**Issue by swsch** [npgsql/doc#259]
On the main documentation page https://www.npgsql.org/doc/index.html 
the "API reference" link to the "plain" Npqsql API docs points to EFCore API docs: https://www.npgsql.org/efcore/api/Microsoft.Extensions.DependencyInjection.html

Where is the non-EFCore API documentation?

**Comment by roji** [comment]
Fixed this in #260, thanks for reporting!
