### ISSUE TITLE
Documentation wrong/incomplete regarding own function calls using select * from <function>

### ISSUE THREAD

**Issue by FransBouma** [npgsql/doc#264]
Regarding this breaking change in Npgsql 7: <https://www.npgsql.org/doc/release-notes/7.0.html#a-namecommandtypestoredprocedure-commandtypestoredprocedure-now-invokes-procedures-instead-of-functions>

Let me first say that I'm **not amused** by this. Enforcing this breaking change upon everyone as an opt-out scenario is IMHO not the way to go: it requires everyone who creates code using Npgsql to know about the opt-out switch (and how long will that switch stay? Will it be removed at some point, breaking things again?) as people simply reference the latest Npgsql from github and assume things will ' just work'

Well, they won't. I now have to add code to change all calls to Functions into `select * from function(param1, param2...)` and all my software with older versions not having this change will potentially run into the risk of this breaking change, and they'll contact us because their app crashed. Thanks for the extra support work! (that was sarcasm btw. ) 

Why not enable these features as opt-in? Especially with stored procedures which are seriously limited on PostgreSQL, are only recently introduced and by all means are likely never used by users unless they need to start a transaction inside a proc. 

Ok, so I set to work to implement the `select * from function...` but ... this gives problems. 
I have a simple function:
```SQL
CREATE OR REPLACE FUNCTION public.pr_getcustomeramount(IN pcountry character varying, OUT pcustomercount integer)
  RETURNS integer AS
$BODY$
BEGIN
	SELECT COUNT(*) INTO pCustomerCount FROM Customers WHERE Country = pCountry;
END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION public.pr_getcustomeramount(character varying)
  OWNER TO postgres;
```
The documentation you provide says, use $1, $2 etc. for parameters. But ... that doesn't work:
```SQL
select * from "public"."pr_getcustomeramount" ($1)
```
gives:
 ```
 Exception type: Npgsql.PostgresException
Message: 08P01: bind message supplies 0 parameters, but prepared statement "" requires 1

Stack-trace:
   at Npgsql.Internal.NpgsqlConnector.<<ReadMessage>g__ReadMessageLong|220_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
```

Only thing that works is specifying it with the `:paramname` variant:
```SQL
select * from "public"."pr_getcustomeramount" (:pcountry)
```

Also, output parameters shouldn't be specified, which isn't clear from the example either

**Comment by roji** [comment]
@FransBouma merged some clarifications to the breaking change note based on the discussion above, thanks for reaching out (even when it includes complaining :rofl: )

**Comment by FransBouma** [comment]
Great! :) 👍
