### ISSUE TITLE
Document that logging support is removed in v7

### ISSUE THREAD

**Issue by acn-sbuad** [npgsql/doc#270]
I found the following note in the [logging documentation.](https://www.npgsql.org/doc/diagnostics/logging.html?q=ConsoleLoggingProvider&tabs=console)

```
Starting with version 7.0, Npgsql supports standard .NET logging via [Microsoft.Extensions.Logging](https://learn.microsoft.com/dotnet/core/extensions/logging). If you're using an earlier version of Npgsql, skip down to [this section](https://www.npgsql.org/doc/diagnostics/logging.html?q=ConsoleLoggingProvider&tabs=console#old-logging).
``` 

Shouldn't this also be mentioned in the[ breaking changes section of the release notes of v7](https://www.npgsql.org/efcore/release-notes/7.0.html#breaking-changes)?

Not sure how to formulate is myself, so creating an issue rather than a PR. Would have saved me a few minutes figuring out why my build was breaking with the new upgrade.

**Comment by roji** [comment]
The new logging is [mentioned](https://www.npgsql.org/doc/release-notes/7.0.html#improved-logging-with-microsoftextensionslogging) as one of the main new features of Npgsql 7.0. But sure, I can add a breaking change note as well.
