### ISSUE TITLE
TCP Keep Alive time is in s, the documentation say ms

### ISSUE THREAD

**Issue by SebastienCaunes** [npgsql/doc#284]
In the documentation https://www.npgsql.org/doc/connection-string-parameters.html
`TCP Keep Alive Time` and `TCP Keep Alive Interval` are supposed to be ms.

The connection string builder property comment says it is seconds. 

I tested and it is seconds.

Please update the documentation. I lost a lot of time trying to troubleshoot the problem due to that.

**Comment by roji** [comment]
Thanks and sorry for the typo. I'm also removing the note about TCP Keepalives being Windows-only, that hasn't been the case for a while now.

**Comment by SebastienCaunes** [comment]
Thank you for being so reactive. It took you less time to correct it than it took me fighting with this.

B.R.

**Comment by roji** [comment]
Unfortunately that's the way it is with docs - a small typo can cause lots of people lots of pain... Sorry again.
