### ISSUE TITLE
Small error on collations docs

### ISSUE THREAD

**Issue by tpoiesz** [npgsql/doc#303]
On https://www.npgsql.org/efcore/misc/collations-and-case-sensitivity.html?tabs=data-annotations it tells us that to use a collation on the database level we need to use `HasCollation`:

![image](https://github.com/npgsql/efcore.pg/assets/25227747/e4a92b8c-d29d-43d0-aa61-ed06e1c9372b)

However, I believe `HasCollation` is used to _create_ a collation, and this code snippet should use `UseCollation`.

**Comment by roji** [comment]
Well-spotted, thanks!
