### ISSUE TITLE
Proposal: Migrate to mkdocs

### ISSUE THREAD

**Issue by djgalvan** [npgsql/doc#332]
I haven't worked with docfx, but I was able to quickly start a migration of the project to mkdocs fairly quickly. I'll spend some time on it if accepted.

[Initial Migration](https://djgalvan.github.io/npgsql-docs/)

**Comment by roji** [comment]
What's the exact advantage in doing this? Also, I don't see API documentation in your sample (generated from the source code), is that supported?

**Comment by djgalvan** [comment]
Oh wow, didn't notice that there was generated API docs in there. Glad I asked before plowing through it. 

I'll do some looking into docfx...
