### ISSUE TITLE
Basic Usage NpgsqlCommand ExecuteReaderAsync Return Value Is Wrong

### ISSUE THREAD

**Issue by onurmx** [npgsql/doc#339]
Hello Everyone!

In Npgsql Basic Usage docs, specifically at [this](https://github.com/npgsql/doc/blob/1489127f744d553096a2d0de44cd1bc27ed5cf30/conceptual/Npgsql/basic-usage.md?plain=1#L41) and [this](https://github.com/npgsql/doc/blob/1489127f744d553096a2d0de44cd1bc27ed5cf30/conceptual/Npgsql/basic-usage.md?plain=1#L43) lines it states that I can use ReadAsync method from directly reader result.

However, in reality ExecuteReaderAsync returns Task<NpgsqlDataReader> and this is already stated at API reference. Can we fix that issue? Thanks in advance.

**Comment by roji** [comment]
@onurmx I don't understand - the docs clearly show an `await` just before ExecuteReaderAsync, as is standard with Task-returning async methods. What do you think needs fixing?

**Comment by onurmx** [comment]
Hi @roji ,

Yes, it is my mistake. Apologies. We can close the issue with no action.

Best regards.
