### ISSUE TITLE
Should remove IntegratedSecurity from the doc

### ISSUE THREAD

**Issue by thohng** [npgsql/doc#340]
IntegratedSecurity was obsoleted, should remove it from document also?

https://github.com/npgsql/doc/blob/main/conceptual/Npgsql/connection-string-parameters.md?plain=1#L14-L15

![image](https://github.com/npgsql/doc/assets/9668549/cc375968-d88d-404e-94fb-412c8feb2969)

Reference:
Issue: https://github.com/npgsql/npgsql/issues/4789
Updates: https://github.com/npgsql/doc/commit/2a4724cc0a0d7d75e2d59ba89038ba9c2abf2dac

**Comment by roji** [comment]
@thohng thanks, done.
