### ISSUE TITLE
I have an optimization suggestion regarding the Npgsql website.

### ISSUE THREAD

**Issue by kyssion** [npgsql/doc#341]
Hello, there is a minor optimization suggestion for the Npgsql website. When I was reviewing the API documentation, I noticed that when there is too much content, the table of contents on the right side might be obscured, resulting in incomplete content visibility.This is a simple CSS styling issue. You can resolve it by modifying the style of the following div element. 

"The web address that can be optimized is this one: https://www.npgsql.org/doc/api/Npgsql.NpgsqlConnection.html#methods"

![Screenshot_20240501_061525](https://github.com/npgsql/npgsql/assets/12844517/fafec25c-f1c2-4aaf-8f51-77e286c162e0)

Simply add the style 'overflow:auto' to the div tag with the class name 'sideaffix'.

The final result will be like this:

![Screenshot_20240501_062020](https://github.com/npgsql/npgsql/assets/12844517/97658555-ae40-455c-b883-8bde55d88ae9)

I didn't find any other way to submit issues about web page modifications, so I submitted it here.

**Comment by roji** [comment]
@kyssion we generally don't tweak the CSS - that's coming from the template provided by the tool we use to generate the docs, which is [docfx](https://dotnet.github.io/docfx/). I recommend submitting a PR to that project, fixing this problem for everyone (not just for Npgsql).
