### ISSUE TITLE
Confusing content in the EFCore > Mapping > Json document

### ISSUE THREAD

**Issue by bbarry** [npgsql/doc#366]
The [EFCore Json document mapping table](https://github.com/npgsql/doc/blob/main/conceptual/EFCore.PG/mapping/json.md/#jsondocument-mapping-1) contains entries that clearly aren't doing the same thing or are invalid sql.

For example:

.NET                                                                                  | SQL
------------------------------------------------------------------------------------- | ----
customer.RootElement.GetProperty("Orders")[1].GetProperty("Price").GetInt32() | customer#>>'{Orders,0,Price}'[1] = 8

Doesn't appear to be valid sql (syntax error at `[`)?

And the C# reads like it should be trying to produce the sql `(customer#>>'{Orders,1,Price})::int` (I don't have a tool at hand to verify this though).

**Comment by roji** [comment]
Thanks, corrected this in da0423581ef07950bc2204f030d239eec2c961c2.
