### ISSUE TITLE
Querying JSON columns section's note cut off

### ISSUE THREAD

**Issue by MonstraG** [npgsql/doc#376]
Note just below the header of this section:
https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco#querying-json-columns-traditional-json-and-dom

goes like this:
```
The below does not apply if you are using ToJson (owned entity mapping). ToJson supports
```

It just cuts off after the word `supports`, there is nothing else.

**Comment by roji** [comment]
Thanks, I pushed a fix for this.
