### ISSUE TITLE
Should "improve this doc" refer to "main" branch?

### ISSUE THREAD

**Issue by Bouke** [npgsql/doc#44]
https://github.com/npgsql/doc/blob/f03d5e398353a46ba9ac1ef6511d6388c9d99e57/docfx.json#L80

There's now both master and main, where main is marked as the default. Should the "improve this doc" now reference this branch as well? Note I'm not familiar with docfx so there might be more to this than the line I referenced.

**Comment by roji** [comment]
Absolutely, thanks for catching this. There in fact shouldn't be a master branch - I did a rename a few weeks back, but mess things up a bit. I just did a clean-up, merging everything from master into main, and deleted master altogether. Would you like to submit a PR to fix the branch?

**Comment by roji** [comment]
Actually, that particular reference is to the master branches under the Npgsql and Npgsql.EntityFrameworkCore.PostgreSQL repos, where master has been renamed to stable. I'll take care of this - thanks again for flagging.
