### ISSUE TITLE
Contribution info on EFCore.PG point to Npgsql

### ISSUE THREAD

**Issue by roji** [npgsql/doc#54]
Our release note [page](http://www.npgsql.org/efcore/release-notes/3.x.html) for EFCore.PG 3.x contains contribution information, but they seem to refer to Npgsql instead of EFCore.PG.

Note that to me it makes sense to unify 3.0 and 3.1 into the same 3.x page (including all their patch version contribution info) - 3.0 is out of support and there's no reason for anyone to use it anymore (plus 3.1 doesn't really improve that much over it).

@Brar do you think you can take a look at this?

**Comment by Brar** [comment]
> @Brar do you think you can take a look at this?

Yes, I'll take care of it.

**Comment by roji** [comment]
Thanks @Brar!
