### ISSUE TITLE
Isn't "Querying JSON columns" inaccurate or outdated?

### ISSUE THREAD

**Issue by fmakowski** [npgsql/doc#58]
Hey, I am trying to replicate a behavior found on [Mapping and Translation/JSON](http://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco#querying-json-columns) page and it seems that `JsonDocument` does not have the `GetProperty` method available. Also, the translation doesn't seem to work. Is there any innacuracy introduced here or maybe the document is simply outdated and it should be done differently?

**Comment by roji** [comment]
Yeah, if you're mapping JsonDocument (as opposed to JsonElement), you must access RootElement which has GetProperty. Would you like to submit a doc PR?
