### ISSUE TITLE
Missing documentation of Include Error Detail in connection-string-parameters.md

### ISSUE THREAD

**Issue by FireEmerald** [npgsql/doc#62]
The page [Connection String Parameters](http://www.npgsql.org/doc/connection-string-parameters.html) of npgsql does not include the `Include Error Detail` switch.

Definition:
https://github.com/npgsql/npgsql/blob/e84f96abf67ca4198787126a00a8b14b1a228be0/src/Npgsql/NpgsqlConnectionStringBuilder.cs#L712-L731

Should be added to:
https://github.com/npgsql/doc/blob/main/conceptual/Npgsql/connection-string-parameters.md

**Comment by YohDeadfall** [comment]
Would you like to submit a PR?

**Comment by FireEmerald** [comment]
I will leave the change up to you without a extra pull request.
