### ISSUE TITLE
Logo svg on mouse over is broken

### ISSUE THREAD

**Issue by latop2604** [npgsql/doc#8]
I have this issue on chrone/firefox/edge

![image](https://user-images.githubusercontent.com/2058133/60954893-10481e00-a300-11e9-8bc4-82010f7136eb.png)

**Comment by austindrenski** [comment]
Oh, that's new, and a bit strange. Thanks for reporting!

**Comment by austindrenski** [comment]
@YohDeadfall Any chance this was caused by 66f7f10f671121a42e0fe34de1bd39b84e25e0bb, and just went unnoticed?

**Comment by austindrenski** [comment]
I'm too out of practice with DocFX to say what the proper fix is, but this seems to be the relevant rule set:

https://github.com/npgsql/doc/blob/6be05d3b2843dc764bbcd2b3b683b942180acf54/docs/styles/docfx.css#L83-L85

**Comment by YohDeadfall** [comment]
Yep, previously we had no `svg` class on the logo.
