### ISSUE TITLE
Creating Jsonb indices using Entity Framework Core Library

### ISSUE THREAD

**Issue by karandesai28** [npgsql/doc#83]
This [documentation](https://www.npgsql.org/efcore/mapping/json.html#indexing-json-columns) still doesn't describe semantics to add indices using Entity Framework Core library for Jsonb fields. Kindly point me to valid documentation for the same. 
Thank You.

**Comment by roji** [comment]
[These PostgreSQL docs](https://www.postgresql.org/docs/current/datatype-json.html#JSON-INDEXING) are probably what you're looking for. You can use [raw SQL](https://docs.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql) in your migrations to create whatever indexes you want.
