### ISSUE TITLE
Full text search examples with EF Core

### ISSUE THREAD

**Issue by dctremblay** [npgsql/doc#93]
I'm trying to do the following but cannot find any help :

- sorted by relevance
- different weight per property (title, description)
- ignore accents

I have tried many ways and  only managed to make this work (which only returns matches) :

```csharp
Entries = Db.Posts.Where(p => p.SearchVector.Matches(Query));
```

```csharp
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Post>()
        .HasGeneratedTsVectorColumn(
            p => p.SearchVector, "english",
            p => new { p.Name, p.Description })
        .HasIndex(p => p.SearchVector).HasMethod("GIN");
```

I think it would  be worth adding in the docs.

**Comment by sowsan** [comment]
same here looking for an example.

**Comment by roji** [comment]
@dctremblay that seems almost like a copy-paste out of the [existing documentation](https://www.npgsql.org/efcore/mapping/full-text-search.html#method-1-tsvector-column)... What am I missing?

**Comment by dctremblay** [comment]
@roji It's what it is

**Comment by roji** [comment]
Oh, I misunderstood your issue, sorry.

You will need to look at the [PostgreSQL docs on full-text search](https://www.npgsql.org/efcore/mapping/full-text-search.html#operation-translation) and understand how to do what you want; the Npgsql EF Core provider only exposes those features via .NET. In other words, we cannot document various full-text scenarios - that would basically duplicate the PG docs.

Though if you look down below in the [operation translation section](https://www.npgsql.org/efcore/mapping/full-text-search.html#operation-translation), you will see the building blocks you're looking for (e.g. EF.Functions.Unaccent, tsVector.Rank...).

**Comment by kirinnee** [comment]
I am still confused. How does the operation translation section allow for generated computed columns like:
```
ALTER TABLE se_details ADD COLUMN ts tsvector
    GENERATED ALWAYS AS
     **(setweight(to_tsvector('english', coalesce(event_narrative, '')), 'A') ||**
     **setweight(to_tsvector('english', coalesce(episode_narrative, '')), 'B'))** STORED;
```
?

**Comment by roji** [comment]
@kirinnee Npgsql won't generate `setweight` for you - HasGeneratedTsVectorColumn only generates the specific SQL which it generates. You can simply insert your custom SQL into the migration [as detailed in the EF docs](https://learn.microsoft.com/en-us/ef/core/managing-schemas/migrations/managing?tabs=dotnet-core-cli#adding-raw-sql).
